version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: follower_production_django
    platform: linux/x86_64
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    networks:
      - proxy
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.follow-secure.entrypoints=websecure"
      - "traefik.http.routers.follow-secure.rule=Host(`follow.africandao.com`)"
      - "traefik.http.routers.follow-secure.service=follow-service"
      - "traefik.http.services.follow-service.loadbalancer.server.port=5000"
      - "traefik.http.middlewares.follow-https-redirect.redirectscheme.scheme=https"

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: follower_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
      - production_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.production/.postgres

  redis:
    image: redis:6

  celeryworker:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    networks:
      - default
    image: follower_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: follower_production_celerybeat
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    networks:
      - default
    command: /start-celerybeat

  flower:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    networks:
      - default
    image: follower_production_flower
    command: /start-flower

networks:
  proxy:
    external: true
