# Generated by Django 3.2.14 on 2022-10-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_me', '0002_auto_20221009_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='OuathStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_token', models.CharField(blank=True, max_length=255, null=True)),
                ('request_secret', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
