# Generated by Django 3.2.14 on 2022-10-14 13:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('follow_me', '0004_autotweets'),
    ]

    operations = [
        migrations.AddField(
            model_name='autotweets',
            name='created_At',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='auto_tweet_status',
            field=models.BooleanField(default=False),
        ),
    ]
