# Generated by Django 3.2.14 on 2022-10-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_me', '0005_auto_20221014_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auto_tweet_interval',
            field=models.CharField(blank=True, default='3 Hours', max_length=500, null=True),
        ),
    ]
