# Generated by Django 3.2.14 on 2022-10-15 13:26

from django.db import migrations, models
import django.db.models.deletion
import django_enum_choices.choice_builders
import django_enum_choices.fields
import follower.follow_me.enums


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0016_alter_crontabschedule_timezone'),
        ('follow_me', '0006_user_auto_tweet_interval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auto_tweet_interval',
        ),
        migrations.RemoveField(
            model_name='user',
            name='auto_tweet_status',
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('Active', 'Active'), ('Disabled', 'Disabled')], default=follower.follow_me.enums.SetupStatus['disabled'], enum_class=follower.follow_me.enums.SetupStatus, max_length=8),
        ),
        migrations.AddField(
            model_name='user',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask'),
        ),
        migrations.AddField(
            model_name='user',
            name='time_interval',
            field=django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('3 hr', '3 hr'), ('6 hr', '6 hr'), ('12 hr', '12 hr')], default=follower.follow_me.enums.TimeInterval['three_hours'], enum_class=follower.follow_me.enums.TimeInterval, max_length=5),
        ),
    ]
