# Generated by Django 3.2.14 on 2022-10-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_me', '0007_auto_20221015_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
